version: "3.9"

services:
  next:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
    container_name: next
    # restart: always
    volumes:
      - ./src:/usr/src
      - ./src/node_modules:/usr/src/node_modules
      - ./src/.next:/usr/src/.next
    ports:
      - 3000:3000
    command: /bin/sh -c "yarn run next"
    # env_file:
    #   - .env
  storybook:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-storybook
    container_name: storybook
    # restart: always
    volumes:
      - ./src:/usr/src
      - ./src/node_modules:/usr/src/node_modules
      - ./src/.next:/usr/src/.next
    ports:
      - 6006:6006
    command: /bin/sh -c "yarn run storybook"
    networks:
      - next-app
    tty: true
volumes:
  node_modules:
networks:
  next-app:
    external: true
